server:
  port: 80
  servlet:
    session:
      cookie:
        max-age: 259200
      timeout: 43200
  compression:
    enabled: true
    mime-types:
      - image/png
      - image/jpeg
      - image/jpg
      - text/html
      - application/javascript
      - text/css
      - application/octet-stream
      - application/json
    min-response-size: 1024
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hsin
    url: jdbc:mysql://localhost:3306/esfm_cd?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        stat:
          enabled: true
      stat-view-servlet:
        enabled: true
#        url-pattern: /*
        login-username: root
        login-password: hsin
      filters: stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /*.js,/*.gif,/*.jpg,/*.png,/*.css,/*.ico,/druid/*
#      aop-patterns: com.esfm.modules.*.dao.*
  servlet:
    multipart:
      max-file-size: 100MB

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: assign_id
      # 默认数据库表下划线命名
      table-underline: true
    #  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#微信公众号配置参数
wx:
  mp:
    appId: wx0c51cbbf1b500f02
    secret: 11eba444755850467112432357f5871a
    token: 111 （接口配置里的Token值）
    aesKey: 111 （接口配置里的EncodingAESKey值）
huawei-auth:
  ak: 7WT5HBWUBGQ2DE9HJDLN
  sk: pVhrcEn4V5lhJkkqcc8wpGV48Pjx2XYByXk0P9vz
  endpoint: obs.cn-south-1.myhuaweicloud.com
